name: Backend Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run linting
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run tests
        run: |
          cd starter/backend
          pipenv run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd starter/backend
          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Docker image built successfully"

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Pushing Docker image..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Docker image pushed successfully"

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name coworking-cluster

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Create deployment manifest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Creating deployment manifest..."
          cat > deployment.yaml << EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            labels:
              app: backend
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                  - name: backend
                    image: $ECR_REGISTRY/backend:$IMAGE_TAG
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 5000
                    resources:
                      requests:
                        memory: "64Mi"
                        cpu: "250m"
                      limits:
                        memory: "128Mi"
                        cpu: "500m"
          EOF
          echo "Deployment manifest created"

      - name: Create service manifest
        run: |
          echo "Creating service manifest..."
          cat > service.yaml << EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: backend
            labels:
              app: backend
          spec:
            type: LoadBalancer
            selector:
              app: backend
            ports:
              - protocol: TCP
                port: 80
                targetPort: 5000
          EOF
          echo "Service manifest created"

      - name: Deploy to EKS
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          echo "Deployment completed"
          echo "Checking pod status..."
          kubectl get pods
          echo "Checking services..."
          kubectl get services